name: Test on Windows
on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the tests with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
  schedule:
    # Run at 8:13 on the 1st day of each month
    - cron:  '13 8 1 * *'
jobs:
  MSVC:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        config:
          - {msvc_version_year: 2019, msvc_version: 16, config: Debug, cxx_standard: 17}
          - {msvc_version_year: 2019, msvc_version: 16, config: Release, cxx_standard: 17}
          - {msvc_version_year: 2019, msvc_version: 16, config: Debug}
          - {msvc_version_year: 2019, msvc_version: 16, config: Release}
          - {msvc_version_year: 2017, msvc_version: 15, config: Debug}
          - {msvc_version_year: 2017, msvc_version: 15, config: Release}
    env:
      PYTHON3_PATH: "C:\\Python36"
      CMAKE_GENERATOR: "Visual Studio ${{matrix.config.msvc_version}} ${{matrix.config.msvc_version_year}}"
      ADDITIONAL_CMAKE_ARGS: -DFRUIT_USES_BOOST=False -T host=x64 -A x64
      CONFIGURATION: ${{matrix.config.config}}
    steps:
      - name: set-cmake-debug-cxx-flags
        if: matrix.config.config == 'Debug'
        run: echo "ADDITIONAL_CMAKE_ARGS=$ADDITIONAL_CMAKE_ARGS -DCMAKE_CXX_FLAGS=\"/WX /DFRUIT_DEBUG /DFRUIT_EXTRA_DEBUG /D_ITERATOR_DEBUG_LEVEL=2\"" >> $GITHUB_ENV
      - name: set-cmake-release-cxx-flags
        if: matrix.config.config == 'Release'
        run: echo "ADDITIONAL_CMAKE_ARGS=$ADDITIONAL_CMAKE_ARGS -DCMAKE_CXX_FLAGS=\"/WX\"" >> $GITHUB_ENV
      - name: set-cmake-cxx-standard-flag
        if: matrix.config.cxx_standard != ''
        run: echo "ADDITIONAL_CMAKE_ARGS=$ADDITIONAL_CMAKE_ARGS -DCMAKE_CXX_STANDARD=${{matrix.config.cxx_standard}}" >> $GITHUB_ENV
      - name: set-explicit-cmake-generator-arch
        # Until version 15 the arch must be specified, after it can't be.
        if: matrix.config.msvc_version < 16
        run: echo "CMAKE_GENERATOR=$CMAKE_GENERATOR Win64" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: install
        shell: cmd
        run: cmd /c extras\scripts\postsubmit.bat
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled && failure() }}

  MinGW:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        config:
          - {use_boost: false, config: Debug, extra_debug: true}
          - {use_boost: false, config: Release}
          - {use_boost: true, config: Release}
          - {use_boost: true, config: Release, disable_shared_libs: true}
    env:
      PYTHON3_PATH: "C:\\Python36"
      CMAKE_GENERATOR: 'MinGW Makefiles'
      MINGW_PATH: 'C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin'
      ADDITIONAL_CMAKE_ARGS: -DBUILD_SHARED_LIBS=${{!matrix.config.disable_shared_libs}}"
      CONFIGURATION: ${{matrix.config.config}}
    steps:
      - name: set-cmake-boost-flags
        if: matrix.config.use_boost
        run: echo "ADDITIONAL_CMAKE_ARGS=$ADDITIONAL_CMAKE_ARGS -DBoost_INCLUDE_DIR=C:\Libraries\boost_1_69_0" >> $GITHUB_ENV
      - name: set-cmake-non-boost-flags
        if: ${{ !matrix.config.use_boost }}
        run: echo "ADDITIONAL_CMAKE_ARGS=$ADDITIONAL_CMAKE_ARGS -DFRUIT_USES_BOOST=False" >> $GITHUB_ENV
      - name: set-cmake-extra-debug-flags
        if: matrix.config.extra_debug
        run: echo "ADDITIONAL_CMAKE_ARGS=$ADDITIONAL_CMAKE_ARGS -DCMAKE_CXX_FLAGS=\"-Werror -DFRUIT_DEBUG=1 -DFRUIT_EXTRA_DEBUG=1 -D_GLIBCXX_DEBUG=1\"" >> $GITHUB_ENV
      - name: set-cmake-no-extra-debug-flags
        if: ${{ !matrix.config.extra_debug }}
        run: echo "ADDITIONAL_CMAKE_ARGS=$ADDITIONAL_CMAKE_ARGS -DCMAKE_CXX_FLAGS=\"-Werror\"" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: install
        shell: cmd
        run: cmd /c extras\scripts\postsubmit.bat
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled && failure() }}
