name: Test on Linux
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  Test-on-Linux:
    runs-on: ubuntu-latest
    container: polettimarco:ubuntu-20.10
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: extras/scripts/postsubmit-helper.sh ReleasePlain
        env:
          COMPILER: gcc-10
          N_JOBS: 2
          STLARG: ""
          ASAN_OPTIONS: ""
          OS: "linux"

#branches:
#  only:
#  - master
#dist: xenial
#language: cpp
#matrix:
#  fast_finish: true
#  include:
#  - compiler: gcc
#    env: COMPILER=gcc-10 UBUNTU=20.10 TEST=ReleasePlain
#    install: export OS=linux; export COMPILER='gcc-10'; export UBUNTU='20.10'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='gcc-10'; export UBUNTU='20.10'; extras/scripts/postsubmit.sh
#      ReleasePlain
#  - compiler: gcc
#    env: COMPILER=gcc-10 UBUNTU=20.10 TEST=DebugPlain
#    install: export OS=linux; export COMPILER='gcc-10'; export UBUNTU='20.10'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='gcc-10'; export UBUNTU='20.10'; extras/scripts/postsubmit.sh
#      DebugPlain
#  - compiler: clang
#    env: COMPILER=clang-8.0 STL=libstdc++ UBUNTU=20.10 TEST=ReleasePlain
#    install: export OS=linux; export COMPILER='clang-8.0'; export STL='libstdc++';
#      export UBUNTU='20.10'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='clang-8.0'; export STL='libstdc++';
#      export UBUNTU='20.10'; extras/scripts/postsubmit.sh ReleasePlain
#  - compiler: clang
#    env: COMPILER=clang-8.0 STL=libstdc++ UBUNTU=20.10 TEST=DebugAsanUbsan
#    install: export OS=linux; export COMPILER='clang-8.0'; export STL='libstdc++';
#      export UBUNTU='20.10'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='clang-8.0'; export STL='libstdc++';
#      export UBUNTU='20.10'; extras/scripts/postsubmit.sh DebugAsanUbsan
#  - compiler: clang
#    env: COMPILER=clang-8.0 STL=libstdc++ UBUNTU=20.10 TEST=DebugPlain
#    install: export OS=linux; export COMPILER='clang-8.0'; export STL='libstdc++';
#      export UBUNTU='20.10'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='clang-8.0'; export STL='libstdc++';
#      export UBUNTU='20.10'; extras/scripts/postsubmit.sh DebugPlain
#  - compiler: clang
#    env: COMPILER=clang-6.0 STL=libstdc++ UBUNTU=20.04 TEST=ReleasePlain
#    install: export OS=linux; export COMPILER='clang-6.0'; export STL='libstdc++';
#      export UBUNTU='20.04'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='clang-6.0'; export STL='libstdc++';
#      export UBUNTU='20.04'; extras/scripts/postsubmit.sh ReleasePlain
#  - compiler: clang
#    env: COMPILER=clang-6.0 STL=libstdc++ UBUNTU=20.04 TEST=DebugAsanUbsan
#    install: export OS=linux; export COMPILER='clang-6.0'; export STL='libstdc++';
#      export UBUNTU='20.04'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='clang-6.0'; export STL='libstdc++';
#      export UBUNTU='20.04'; extras/scripts/postsubmit.sh DebugAsanUbsan
#  - compiler: clang
#    env: COMPILER=clang-6.0 STL=libstdc++ UBUNTU=20.04 TEST=DebugPlain
#    install: export OS=linux; export COMPILER='clang-6.0'; export STL='libstdc++';
#      export UBUNTU='20.04'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='clang-6.0'; export STL='libstdc++';
#      export UBUNTU='20.04'; extras/scripts/postsubmit.sh DebugPlain
#  - compiler: gcc
#    env: COMPILER=bazel UBUNTU=18.04
#    install: export OS=linux; export COMPILER='bazel'; export UBUNTU='18.04'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='bazel'; export UBUNTU='18.04'; extras/scripts/postsubmit.sh
#      DebugPlain
#  - compiler: gcc
#    env: COMPILER=gcc-7 UBUNTU=20.10 TEST=ReleasePlain
#    install: export OS=linux; export COMPILER='gcc-7'; export UBUNTU='20.10'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='gcc-7'; export UBUNTU='20.10'; extras/scripts/postsubmit.sh
#      ReleasePlain
#  - compiler: gcc
#    env: COMPILER=gcc-7 UBUNTU=20.10 TEST=DebugAsanUbsan
#    install: export OS=linux; export COMPILER='gcc-7'; export UBUNTU='20.10'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='gcc-7'; export UBUNTU='20.10'; extras/scripts/postsubmit.sh
#      DebugAsanUbsan
#  - compiler: gcc
#    env: COMPILER=gcc-10 UBUNTU=20.10 TEST=DebugAsanUbsan
#    install: export OS=linux; export COMPILER='gcc-10'; export UBUNTU='20.10'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='gcc-10'; export UBUNTU='20.10'; extras/scripts/postsubmit.sh
#      DebugAsanUbsan
#  - compiler: clang
#    env: COMPILER=clang-11.0 STL=libstdc++ UBUNTU=20.10 TEST=ReleasePlain
#    install: export OS=linux; export COMPILER='clang-11.0'; export STL='libstdc++';
#      export UBUNTU='20.10'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='clang-11.0'; export STL='libstdc++';
#      export UBUNTU='20.10'; extras/scripts/postsubmit.sh ReleasePlain
#  - compiler: clang
#    env: COMPILER=clang-11.0 STL=libstdc++ UBUNTU=20.10 TEST=DebugAsanUbsan
#    install: export OS=linux; export COMPILER='clang-11.0'; export STL='libstdc++';
#      export UBUNTU='20.10'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='clang-11.0'; export STL='libstdc++';
#      export UBUNTU='20.10'; extras/scripts/postsubmit.sh DebugAsanUbsan
#  - compiler: clang
#    env: COMPILER=clang-11.0 STL=libc++ UBUNTU=20.10 TEST=ReleasePlain
#    install: export OS=linux; export COMPILER='clang-11.0'; export STL='libc++'; export
#      UBUNTU='20.10'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='clang-11.0'; export STL='libc++'; export
#      UBUNTU='20.10'; extras/scripts/postsubmit.sh ReleasePlain
#  - compiler: clang
#    env: COMPILER=clang-11.0 STL=libc++ UBUNTU=20.10 TEST=DebugAsanUbsan
#    install: export OS=linux; export COMPILER='clang-11.0'; export STL='libc++'; export
#      UBUNTU='20.10'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='clang-11.0'; export STL='libc++'; export
#      UBUNTU='20.10'; extras/scripts/postsubmit.sh DebugAsanUbsan
#  - compiler: gcc
#    env: COMPILER=gcc-7 UBUNTU=20.04 TEST=ReleasePlain
#    install: export OS=linux; export COMPILER='gcc-7'; export UBUNTU='20.04'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='gcc-7'; export UBUNTU='20.04'; extras/scripts/postsubmit.sh
#      ReleasePlain
#  - compiler: gcc
#    env: COMPILER=gcc-7 UBUNTU=20.04 TEST=DebugAsanUbsan
#    install: export OS=linux; export COMPILER='gcc-7'; export UBUNTU='20.04'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='gcc-7'; export UBUNTU='20.04'; extras/scripts/postsubmit.sh
#      DebugAsanUbsan
#  - compiler: gcc
#    env: COMPILER=gcc-5 UBUNTU=18.04 TEST=ReleasePlain
#    install: export OS=linux; export COMPILER='gcc-5'; export UBUNTU='18.04'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='gcc-5'; export UBUNTU='18.04'; extras/scripts/postsubmit.sh
#      ReleasePlain
#  - compiler: gcc
#    env: COMPILER=gcc-5 UBUNTU=18.04 TEST=DebugPlain
#    install: export OS=linux; export COMPILER='gcc-5'; export UBUNTU='18.04'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='gcc-5'; export UBUNTU='18.04'; extras/scripts/postsubmit.sh
#      DebugPlain
#  - compiler: gcc
#    env: COMPILER=gcc-8 UBUNTU=18.04 TEST=ReleasePlain
#    install: export OS=linux; export COMPILER='gcc-8'; export UBUNTU='18.04'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='gcc-8'; export UBUNTU='18.04'; extras/scripts/postsubmit.sh
#      ReleasePlain
#  - compiler: gcc
#    env: COMPILER=gcc-8 UBUNTU=18.04 TEST=DebugPlain
#    install: export OS=linux; export COMPILER='gcc-8'; export UBUNTU='18.04'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='gcc-8'; export UBUNTU='18.04'; extras/scripts/postsubmit.sh
#      DebugPlain
#  - compiler: clang
#    env: COMPILER=clang-3.9 STL=libstdc++ UBUNTU=18.04 TEST=ReleasePlain
#    install: export OS=linux; export COMPILER='clang-3.9'; export STL='libstdc++';
#      export UBUNTU='18.04'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='clang-3.9'; export STL='libstdc++';
#      export UBUNTU='18.04'; extras/scripts/postsubmit.sh ReleasePlain
#  - compiler: clang
#    env: COMPILER=clang-3.9 STL=libstdc++ UBUNTU=18.04 TEST=DebugAsanUbsan
#    install: export OS=linux; export COMPILER='clang-3.9'; export STL='libstdc++';
#      export UBUNTU='18.04'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='clang-3.9'; export STL='libstdc++';
#      export UBUNTU='18.04'; extras/scripts/postsubmit.sh DebugAsanUbsan
#  - compiler: clang
#    env: COMPILER=clang-7.0 STL=libstdc++ UBUNTU=18.04 TEST=ReleasePlainNoPch
#    install: export OS=linux; export COMPILER='clang-7.0'; export STL='libstdc++';
#      export UBUNTU='18.04'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='clang-7.0'; export STL='libstdc++';
#      export UBUNTU='18.04'; extras/scripts/postsubmit.sh ReleasePlainNoPch
#  - compiler: clang
#    env: COMPILER=clang-7.0 STL=libstdc++ UBUNTU=18.04 TEST=DebugAsanUbsanNoPch
#    install: export OS=linux; export COMPILER='clang-7.0'; export STL='libstdc++';
#      export UBUNTU='18.04'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='clang-7.0'; export STL='libstdc++';
#      export UBUNTU='18.04'; extras/scripts/postsubmit.sh DebugAsanUbsanNoPch
#  - compiler: gcc
#    env: COMPILER=gcc-5 UBUNTU=16.04 TEST=ReleasePlain
#    install: export OS=linux; export COMPILER='gcc-5'; export UBUNTU='16.04'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='gcc-5'; export UBUNTU='16.04'; extras/scripts/postsubmit.sh
#      ReleasePlain
#  - compiler: gcc
#    env: COMPILER=gcc-5 UBUNTU=16.04 TEST=DebugPlain
#    install: export OS=linux; export COMPILER='gcc-5'; export UBUNTU='16.04'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='gcc-5'; export UBUNTU='16.04'; extras/scripts/postsubmit.sh
#      DebugPlain
#  - compiler: clang
#    env: COMPILER=clang-3.5 STL=libstdc++ UBUNTU=16.04 TEST=ReleasePlain
#    install: export OS=linux; export COMPILER='clang-3.5'; export STL='libstdc++';
#      export UBUNTU='16.04'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='clang-3.5'; export STL='libstdc++';
#      export UBUNTU='16.04'; extras/scripts/postsubmit.sh ReleasePlain
#  - compiler: clang
#    env: COMPILER=clang-3.5 STL=libstdc++ UBUNTU=16.04 TEST=DebugPlain
#    install: export OS=linux; export COMPILER='clang-3.5'; export STL='libstdc++';
#      export UBUNTU='16.04'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='clang-3.5'; export STL='libstdc++';
#      export UBUNTU='16.04'; extras/scripts/postsubmit.sh DebugPlain
#  - compiler: clang
#    env: COMPILER=clang-3.9 STL=libstdc++ UBUNTU=16.04 TEST=ReleasePlain
#    install: export OS=linux; export COMPILER='clang-3.9'; export STL='libstdc++';
#      export UBUNTU='16.04'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='clang-3.9'; export STL='libstdc++';
#      export UBUNTU='16.04'; extras/scripts/postsubmit.sh ReleasePlain
#  - compiler: clang
#    env: COMPILER=clang-3.9 STL=libstdc++ UBUNTU=16.04 TEST=DebugPlain
#    install: export OS=linux; export COMPILER='clang-3.9'; export STL='libstdc++';
#      export UBUNTU='16.04'; extras/scripts/travis_ci_install_linux.sh
#    os: linux
#    script: export OS=linux; export COMPILER='clang-3.9'; export STL='libstdc++';
#      export UBUNTU='16.04'; extras/scripts/postsubmit.sh DebugPlain
#services:
#- docker
#sudo: required
#
