name: Test on Windows
on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the tests with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
  schedule:
    # Run at 8:13 on the 1st day of each month
    - cron:  '13 8 1 * *'
jobs:
  MSVC:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        config:
          - {msvc_version_year: 2019, msvc_version: 16, config: Debug, cxx_standard: 17}
          - {msvc_version_year: 2019, msvc_version: 16, config: Release, cxx_standard: 17}
          - {msvc_version_year: 2019, msvc_version: 16, config: Debug}
          - {msvc_version_year: 2019, msvc_version: 16, config: Release}
          - {msvc_version_year: 2017, msvc_version: 15, config: Debug}
          - {msvc_version_year: 2017, msvc_version: 15, config: Release}
    env:
      PYTHON3_PATH: "C:\\Python36"
      CMAKE_GENERATOR: "Visual Studio ${{matrix.config.msvc_version}} ${{matrix.config.msvc_version_year}} Win64"
      ADDITIONAL_CMAKE_ARGS: "-DFRUIT_USES_BOOST=False -T host=x64 -A x64 ${{ if(matrix.config.config == 'Debug', '-DCMAKE_CXX_FLAGS="/WX /DFRUIT_DEBUG /DFRUIT_EXTRA_DEBUG /D_ITERATOR_DEBUG_LEVEL=2"', '-DCMAKE_CXX_FLAGS="/WX"') }} ${{ if(matrix.config.cxx_standard == '', '', format('-DCMAKE_CXX_STANDARD={0}', matrix.config.cxx_standard)) }}"
      CONFIGURATION: ${{matrix.config.config}}
    steps:
      - uses: actions/checkout@v2
      - name: install
        shell: cmd
        run: cmd /c extras\scripts\postsubmit.bat
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled && failure() }}

  MinGW:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        config:
          - {use_boost: false, config: Debug, extra_debug: true}
          - {use_boost: false, config: Release}
          - {use_boost: true, config: Release}
          - {use_boost: true, config: Release, disable_shared_libs: true}
    env:
      PYTHON3_PATH: "C:\\Python36"
      CMAKE_GENERATOR: 'MinGW Makefiles'
      MINGW_PATH: 'C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin'
      ADDITIONAL_CMAKE_ARGS: '${{if(matrix.config.use_boost, '-DBoost_INCLUDE_DIR=C:\Libraries\boost_1_69_0', '-DFRUIT_USES_BOOST=False')}} -DBUILD_SHARED_LIBS=${{!matrix.config.disable_shared_libs}} -DCMAKE_CXX_FLAGS="-Werror ${{if(matrix.config.extra_debug, '-DFRUIT_DEBUG=1 -DFRUIT_EXTRA_DEBUG=1 -D_GLIBCXX_DEBUG=1', '')}}"'
    steps:
      - uses: actions/checkout@v2
      - name: install
        shell: cmd
        run: cmd /c extras\scripts\postsubmit.bat
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled && failure() }}
