name: Test on Linux
on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the tests with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
  schedule:
    # Run at 8:13 on the 1st day of each month
    - cron:  '13 8 1 * *'
jobs:
  Ubuntu-20-10:
    runs-on: ubuntu-latest
    container: polettimarco/fruit-basesystem:ubuntu-20.10
    env:
      N_JOBS: 2
      ASAN_OPTIONS: ""
      OS: "linux"
      COMPILER: ${{ matrix.config.compiler }}
      STLARG: ${{ matrix.config.stlarg }}
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: extras/scripts/postsubmit-helper.sh ${{ matrix.config.test }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled && failure() }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {compiler: clang-11.0, stlarg: -stdlib=libstdc++, test: ReleasePlain}
          - {compiler: clang-11.0, stlarg: -stdlib=libstdc++, test: DebugAsanUbsan}
          - {compiler: clang-11.0, stlarg: -stdlib=libc++, test: ReleasePlain}
          - {compiler: clang-11.0, stlarg: -stdlib=libc++, test: DebugAsanUbsan}
          - {compiler: gcc-10, test: ReleasePlain}
          - {compiler: gcc-10, test: DebugPlain}
          - {compiler: gcc-10, test: DebugAsanUbsan}
          - {compiler: clang-8.0, stlarg: -stdlib=libstdc++, test: ReleasePlainNoPch}
          - {compiler: clang-8.0, stlarg: -stdlib=libstdc++, test: DebugPlainNoPch}
          - {compiler: clang-8.0, stlarg: -stdlib=libstdc++, test: DebugAsanUbsanNoPch}
          - {compiler: gcc-7, test: ReleasePlain}
          - {compiler: gcc-7, test: DebugAsanUbsan}

  Ubuntu-20-04:
    runs-on: ubuntu-latest
    container: polettimarco/fruit-basesystem:ubuntu-20.04
    env:
      N_JOBS: 2
      ASAN_OPTIONS: ""
      OS: "linux"
      COMPILER: ${{ matrix.config.compiler }}
      STLARG: ${{ matrix.config.stlarg }}
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: extras/scripts/postsubmit-helper.sh ${{ matrix.config.test }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled && failure() }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {compiler: clang-6.0, stlarg: -stdlib=libstdc++, test: ReleasePlain}
          - {compiler: clang-6.0, stlarg: -stdlib=libstdc++, test: DebugPlain}
          - {compiler: clang-6.0, stlarg: -stdlib=libstdc++, test: DebugAsanUbsan}
          - {compiler: gcc-7, test: ReleasePlain}
          - {compiler: gcc-7, test: DebugAsanUbsan}

  Ubuntu-18-04:
    runs-on: ubuntu-latest
    container: polettimarco/fruit-basesystem:ubuntu-18.04
    env:
      N_JOBS: 2
      ASAN_OPTIONS: ""
      OS: "linux"
      COMPILER: ${{ matrix.config.compiler }}
      STLARG: ${{ matrix.config.stlarg }}
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: extras/scripts/postsubmit-helper.sh ${{ matrix.config.test }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled && failure() }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {compiler: clang-7.0, stlarg: -stdlib=libstdc++, test: ReleasePlainNoPch}
          - {compiler: clang-7.0, stlarg: -stdlib=libstdc++, test: DebugAsanUbsanNoPch}
          - {compiler: gcc-8, test: ReleasePlain}
          - {compiler: gcc-8, test: DebugPlain}
          - {compiler: clang-3.9, stlarg: -stdlib=libstdc++, test: ReleasePlain}
          - {compiler: clang-3.9, stlarg: -stdlib=libstdc++, test: DebugAsanUbsan}
          - {compiler: gcc-5, test: ReleasePlain}
          - {compiler: gcc-5, test: DebugPlain}
          - {compiler: bazel, test: DebugPlain}

  Ubuntu-16-04:
    runs-on: ubuntu-latest
    container: polettimarco/fruit-basesystem:ubuntu-16.04
    env:
      N_JOBS: 2
      ASAN_OPTIONS: ""
      OS: "linux"
      COMPILER: ${{ matrix.config.compiler }}
      STLARG: ${{ matrix.config.stlarg }}
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: extras/scripts/postsubmit-helper.sh ${{ matrix.config.test }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled && failure() }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {ubuntu: "16.04", compiler: clang-3.9, stlarg: -stdlib=libstdc++, test: ReleasePlain}
          - {ubuntu: "16.04", compiler: clang-3.9, stlarg: -stdlib=libstdc++, test: DebugPlain}
          - {ubuntu: "16.04", compiler: gcc-5, test: ReleasePlain}
          - {ubuntu: "16.04", compiler: gcc-5, test: DebugPlain}
          - {ubuntu: "16.04", compiler: clang-3.5, stlarg: -stdlib=libstdc++, test: ReleasePlain}
          - {ubuntu: "16.04", compiler: clang-3.5, stlarg: -stdlib=libstdc++, test: DebugPlain}
